# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3715e5f0db97b2413802be6f5b65c1226ad035ffbb4d4b683226079f9beed100021ff8d7501f5730b4847c3e95c95050963ae966146617bab6eeaee9f8e2dd2

test:
  secret_key_base: 390daa525cd5675f9971c26d075f2c61fa1ff0293956c2e983f03350409bcbb0f49bc106754fdda6bd888e2e56eabca5c2bea2e915f2e0e901ae3a8bd2d08e9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
